### ISSUE TITLE
Emperor 1280x720 Really Needed

### ISSUE THREAD

**Issue by Ophidon** [XJDHDR/impressions-resolution-customiser#1]
Hey there,

Not sure if the project is still active or not, but I just thought I'd point out that the most aggravating oversight in all of the current widescreen solutions for these impressions games is the lack of a 1280x720 option for Emperor. 720p exists as an option for all the other caesar3->zeus games (via julius for caesar 3). And you say you were close to Emperor release, so I sure hope it gets there, and if not maybe I could get a 'pre-release' copy to mess around with somehow?

The existing Emperor widescreen pack has 1280x800, and just about every -other- 16:9 resolution, but not 720p for some unknown reason. 720p is much more important than you might realize at first glance in this era where a lot of pc users are moving to 1440p. The 1440p solution that does exist, is far too zoomed out with far too small of a UI for older eyes. 

720p allows 2x integer scaling to 1440p to get rid of the awful bi-linear interpolation blur, and has a much, much more pleasant zoom factor and ui size. For the 4k (and very long term 8k) future, that isn't -as- bad, as 1080p integer scales to 4k/8k, and the 1080p solutions are far more usable than the current 1440p ones.

**Comment by XJDHDR** [comment]
This project is still active, I've just been very busy recently with other things. I do this as a hobby in my free time and so, it will be done when it's done. 
If you want a pre-release copy, you're welcome to compile the source code to get one. Of course, if you do that, you're on your own for support.

**Edit:** And another thing: Why are you asking for a 1280x720 resolution specifically? Do you not know what this project does?

**Comment by XJDHDR** [comment]
I've just released a resolution patcher for Emperor. You can find it here: https://www.nexusmods.com/emperorriseofthemiddlekingdom/mods/1

It supports a bunch of resolutions; including 1280x720:
![Menu - 720p](https://user-images.githubusercontent.com/7355441/151756009-224f85fa-5b0f-44de-9d5d-bdb1d71e203c.jpg)
![Game - 720p](https://user-images.githubusercontent.com/7355441/151756013-159acfe0-3ee3-46f7-83b9-04004cd61fc5.jpg)

**Comment by factoidforrest** [comment]
So, there's actually a _major_ issue with this and you can see it right in the screenshot you posted. Not sure if it exists for other resolutions but I doubt it. The bottom of the screen is cutoff!

@XJDHDR
