### ISSUE TITLE
Request patch for Ita emperor distribuition

### ISSUE THREAD

**Issue by Dadigno** [XJDHDR/impressions-resolution-customiser#3]
Hi, I have an italian distribution of emperor and your patch not works as expected.

I get: _Emperor.exe was not recognised...._

I hope could be usefull to do the new patch!

Thanks a lot!
Bye #

**Comment by XJDHDR** [comment]
Good day Dadigno

Yes, I am willing to add support for the Italian version.

**Comment by Dadigno** [comment]
I uploaded it on my mega cloud. Let me note if it is enough.

https://mega.nz/file/BhckEKjB#xC6AR_JMKCAtE3LVtjzZJqdXehWBdv1BEpHl97M-Iec

Thanks

**Comment by XJDHDR** [comment]
Just wanted to give an update. I've been working on this for the last week, and here are some screenshots of what I have so far. I just have to fix the part of my code that closes the holes in the UI at the top and right side, and squash a few bugs. After that, Italian support should be ready for release.
![Main menu](https://user-images.githubusercontent.com/7355441/183204463-3b9dc812-9378-48c1-a9c7-240e211c930b.jpg)
![Game](https://user-images.githubusercontent.com/7355441/183202909-126f1e03-7817-45e8-878e-6d4cfd88d0fd.jpg)

**Comment by Dadigno** [comment]
Great job! This is a very good patch!
Thanks a lot for your work, but take your time. I don't want stress you!

Have a nice day

Il ven 5 ago 2022, 23:21 XJDHDR ***@***.***> ha scritto:

**Comment by XJDHDR** [comment]
I've just released a new version of the Emperor Resolution Customiser which, amongst other things, adds support for the Italian version of the game. Hope you enjoy it.

And don't worry about it. I only work on these and my other projects in my free time. It doesn't stress me.
